### ISSUE TITLE
scrollView.pinEdgesToSuperView()

### ISSUE THREAD

**Issue by texyz** [amerhukic/SwipeableCollectionViewCell-Example#1]
Hi,
Thanks for your wonderful solution but i keep on getting

**(Value of type 'UIScrollView' has no member 'pinEdgesToSuperView')**

**Comment by amerhukic** [comment]
Hi @texyz. If you used the code in a different project you must have forgotten to include the UIView+Anchors file with extension that contains that method: https://github.com/amerhukic/SwipeableCollectionViewCell-Example/blob/master/SwipeableCollectionViewCell-Example/UIView%2BAnchors.swift
